# Let's try to keep resolver at the first day of the month
resolver: nightly-2018-01-01
packages:
- servant-client/
- servant-client-core/
- servant-docs/
- servant-foreign/
- servant-server/
- servant/

extra-deps:
- cabal-doctest-1.0.6
- http-api-data-0.3.7.2
- http-types-0.12
- text-1.2.3.0

# allow-newer: true # ignores all bounds, that's a sledgehammer
# - doc/tutorial/
